apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: magento-db-pvc
spec:
  volumeName: magento-db-pv
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
