---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: source-pvc
  namespace: default
spec:
  volumeName: source-pv
  storageClassName: standard
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
