kind: PersistentVolume
apiVersion: v1
metadata:
  name: magento-db-pv
  labels:
    type: front
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db"

