apiVersion: v1
kind: Service
metadata:
  name: front
  labels:
    app: front
spec:
  ports:
    - port: 80
  selector:
    app: front
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: front
  labels:
    app: front
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: front
      tier: frontend
  template:
    metadata:
      labels:
        app: front
        tier: frontend
    spec:
      containers:
      - image: akril/magento:v1
        name: magento
        ports:
        - containerPort: 80
          name: magento
        imagePullPolicy: Never
        volumeMounts:
        - name: source
          mountPath: /app/src/
      volumes:
      - name: source
        persistentVolumeClaim:
          claimName: source-pvc
